mysite/bible/urls.py
from django.urls import path
from . import views

app_name = 'bible'

urlpatterns = [
    path('<str:book>/<int:chapter>', views.index, name='root'),
    path('', views.index, name='root_from_users'),
    path('ajaxreadnote', views.ajaxreadnote, name='ajaxreadnote'),
    path('ajaxwritenote', views.ajaxwritenote, name='ajaxwritenote'),
]

mysite/mysite/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('bible/', include('bible.urls')),
    path('user/', include('users.urls')),
]

mysite/users/urls.py
from django.urls import path
from . import views

app_name = 'users'

urlpatterns = [
    path('signup/', views.signupuser, name='signup'),
    path('login/', views.loginuser, name='login'),
    path('logout/', views.logoutuser, name='logout'),
]

mysite/bible/models.py
from django.db import models
from django.db.models import ForeignKey, IntegerField, TextField, CASCADE, CharField
# Create your models here.


class Book(models.Model):
    name = TextField(max_length=100)
    bible_name = CharField(10, null=True)
    author = TextField()
    when = TextField()
    where = TextField()
    whom = TextField()
    topic = TextField()
    chapter_count = IntegerField(null=True)
    chapter_ready = IntegerField(null=True)

    class Meta:
        indexes = [
            models.Index(fields=['bible_name'])
        ]


class Testament(models.Model):
    name = TextField(max_length=14)


class Verse(models.Model):
    text = TextField()
    chapter = IntegerField(null=False, default=1)
    verse = IntegerField(null=False, default=1)
    testament = ForeignKey(Testament, on_delete=CASCADE)
    book = ForeignKey(Book, on_delete=CASCADE)

    class Meta:
        ordering = ['chapter', 'verse']

class Note(models.Model):
    verse = models.ForeignKey(Verse, on_delete=CASCADE)
    user = models.IntegerField(null=True)
    text = models.TextField()

mysite/users/models.py
from django.db import models

# Create your models here.

mysite/users/forms.py
from django import forms
from django.contrib.auth.forms import UserCreationForm
from django.contrib.auth.models import User
from django.contrib.auth.forms import UserCreationForm, AuthenticationForm



class RegisterForm(UserCreationForm):
    username = forms.CharField(max_length=100,
                               required=True,
                               widget=forms.TextInput())
    email = forms.EmailField(max_length=50, required=True,
                             widget=forms.TextInput())

    password1 = forms.CharField(max_length=50,
                                required=True,
                                widget=forms.PasswordInput())
    password2 = forms.CharField(max_length=50,
                                required=True,
                                widget=forms.PasswordInput())

    class Meta:
        model = User
        fields = ['username', 'email', 'password1', 'password2']


class LoginForm(AuthenticationForm):

    class Meta:
        model = User
        fields = ['username', 'password']

mysite/bible/views.py
import pickle
from django.shortcuts import render
from django.core.cache import cache
from django.http import JsonResponse
from .models import Verse, Book, Note
from .sevices import make_text_linked
from django.db.models import Q


def index(request, book: str='matt', chapter: int=1):
    # список віршів для виводу на сторінку
    verses_to_page = []
    user = pickle.loads(cache.get('user'))  if cache.get('user') else None
    # Завантажуємо вірші з redis. Якщо помінялась книга, то вірші будуть завантажені з нової книги
    verses = cache.get('verses') if (cache.get('book') == book) else None
    # завантажуємо дані книги з redis.
    book_data = cache.get('book_data')
    # якщо даних книги немає, то завантажуємо і кешуємо дані
    if not book_data:
        book_data = Book.objects.filter(bible_name=book).get()  # noqa
        cache.set('book_data', pickle.dumps(book_data))
    else:
        book_data = pickle.loads(book_data)
    # якщо кешованих віршів немає, то завантажуємо і кешуємо їх
    if not verses:
        verses = Verse.objects.filter(book=book_data.id).all()
        cache.set('verses', pickle.dumps(verses))
        # кешуємо назву книги
        cache.set('book', book)
    else:
        verses = pickle.loads(verses)
    # готуємо список віршів дял виведення
    for verse in verses:
        if verse.chapter == chapter:
            verses_to_page.append(verse)
    next_page = chapter + 1 if chapter < book_data.chapter_ready else None
    prev_page = chapter - 1 if chapter > 1 else None

    verses = make_text_linked(verses=verses_to_page)
    context = {'verses': verses,
               'next_page': next_page,
               'prev_page': prev_page,
               'book_name': book_data.name,
               'book': book,
               'user':user,
               }
    return render(request, 'bible/verses.html', context=context)


# Create your views here


def ajaxreadnote(request):
    answer = ''
    uuid = 0
    userid = request.user.id
    if request.method == "POST":
        uuid = request.POST.get('uuid')
        note_text = Note.objects.filter(Q(verse_id=str(uuid)) & Q(user=userid)) # noqa
        if note_text:
            answer = note_text[0].text
    return JsonResponse({'result': answer, 'uuid': uuid}, status=200)


def ajaxwritenote(request):
    text = ''
    userid = request.user.id
    if request.method == "POST":
        text = request.POST.get('text')
        uuid = request.POST.get('uuid')
        note = Note.objects.filter(Q(verse_id=uuid) & Q(user=userid)).first() # noqa
        if not note:
            note = Note(verse_id=uuid, text=text, user=userid)
        else:
            note.text = text
        note.save() 
    return JsonResponse({'result': text}, status=200)

mysite/users/views.py
from django.contrib import messages
from django.shortcuts import render, redirect
from django.contrib.auth import authenticate, login, logout
from .forms import RegisterForm, LoginForm
from django.contrib.auth.decorators import login_required
import pickle
from django.core.cache import cache


def signupuser(request):
    if request.user.is_authenticated:
        return redirect(to='bible:root_from_users')

    if request.method == 'POST':
        form = RegisterForm(request.POST)
        if form.is_valid():
            form.save()
            return redirect(to='users:login')
        else:
            return render(request, 'users/signup.html', context={"form": form})

    return render(request, 'users/signup.html', context={"form": RegisterForm()})


def loginuser(request):
    if request.user.is_authenticated:
        return redirect(to='bible:root_from_users')

    if request.method == 'POST':
        user = authenticate(username=request.POST['username'], password=request.POST['password'])
        if user is None:
            messages.error(request, 'Username or password didn\'t match')
            return redirect(to='users:login')
        login(request, user)
        cache.set('user', pickle.dumps(request.user), timeout=None)
        return redirect(to='bible:root_from_users')

    return render(request, 'users/login.html', context={"form": LoginForm()})


@login_required
def logoutuser(request):
    logout(request)
    if cache.get('user'):
        cache.delete('user')
    return redirect(to='bible:root_from_users')

mysite/bible/templates/bible/base.html
<!DOCTYPE html>
<html lang="en">

<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <title>Біблія - читати онлайн</title>
    <link href="https://fonts.googleapis.com/icon?family=Material+Icons"
      rel="stylesheet">
    <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.7.0/jquery.min.js"></script>
    
    {% load static %}
    <link rel="stylesheet" href="{% static 'bible/style.css' %}">
</head>

<body>
    <nav>
        {% if not user %}
        <a href="{% url 'users:login' %}"><button>Увійти</button></a>
        <a href="{% url 'users:signup' %}"><button>Реєстрація</button></a>
        {% endif %}
        {% if user %}
        <a href="{% url 'users:logout' %}"><button>Вийти&#160&#160<b>{{user.username}}</b></button></a>
        {% endif %}
    </nav>
    {% block header %} {% endblock %}
    
    <main>
        {% block content %} {% endblock %}
    </main>

    <dialog id="modal">  
            {% csrf_token %}
            <header>
                <span id="modal_verse_text"></span>
                <i class="material-icons" onclick="hideModal()">close</i>
            </header>
            <textarea rows="25" name="note_text" id="note_text" placeholder="без коментара"></textarea>
            <nav class="dialog_nav">
                <input type="button" uuid=0 value="Зберегти зміни" id="submit" onclick="customSubmit(this)">
                <input type="button" onclick="undoDeleteText(scope='undo')" value="Відмінити зміни">
                <input type="button" onclick="undoDeleteText(scope='delete')" value = "Видалити все">
            </nav>
    </dialog>

<script>
var undoVerseText = null;

$(document).ready(() => {
    objs = document.querySelectorAll(".click_no_propagation");
    objs.forEach(obj => {
        obj.addEventListener("click", (event)=>{
            event.stopPropagation();
        })
    });
})


function openModal(obj, uuid){
    const csrf = document.querySelector('input[name="csrfmiddlewaretoken"]').value;
    var submit_btn = document.querySelector("#submit");
    var text = document.querySelector("#modal_verse_text");
    var verseText = obj.childNodes[3].childNodes[1].innerHTML;
    // verseText = verseText.replace(/<(a|s|b).{1,25}>/g,'');
    text.innerHTML = verseText;
    submit_btn.setAttribute('uuid', uuid)
    $.ajax({
        type: 'post',
        url: "{% url 'bible:ajaxreadnote' %}",
        data: {csrfmiddlewaretoken: csrf, 'uuid': uuid},
        cache:true,
        success: function(response) {
            var textarea = document.getElementById("note_text");
            textarea.value = response.result;
            undoVerseText = response.result;
            submit_btn.code = response.uuid;
            var modal = document.querySelector("#modal");
            modal.showModal();
            modal.style.display = 'flex';
            textarea.focus();
            textarea.scrollTop = 0;
        }
    })
}

function hideModal(){
    textarea = document.querySelector("#note_text");
    textarea.style.width = '';
    textarea.style.height = '';
    resetModal();
    modal.close();
}

function customSubmit(){
    var text = document.querySelector("#note_text");
    var btn = document.querySelector("#submit");
    var csrf = document.querySelector('input[name="csrfmiddlewaretoken"]').value;
    $.ajax({
        type:'post',
        url: "{% url 'bible:ajaxwritenote' %}",
        data: {'text': text.value, 'uuid':btn.getAttribute('uuid'), csrfmiddlewaretoken: csrf},
        success:function(response){
            console.log(response.text);
        }
    });
    hideModal();
}
function undoDeleteText(scope){
    var text = document.querySelector("#note_text");
    if (scope == 'undo'){
        text.value = undoVerseText;
    } else {
        text.value = "";
    }
}

function resetModal() {
    modal = document.querySelector("#modal");
    modal.style.display = "none";
    modal.style.width = '';
    modal.style.height = '';
}
</script>
</body>

</html>

mysite/bible/templates/bible/root.html
{% extends "bible/base.html" %}
{% block content %}
{% autoescape off %}
{% for verse in verses %}
<div class="row" onclick="openModal(this)">
    <div class="row_verse_number click_no_propagation">
        <span>{{verse.chapter}}:{{verse.verse}}</span>
    </div>
    <div class="row_verse_text click_no_propagation">
        <span>{{verse.text}}</span>
    </div>
    <div class="row_note_icon">
        <i class="material-icons">edit_note</i>
    </div>
</div>
{% endfor %}
{% endautoescape %}
{% endblock %}

mysite/bible/templates/bible/verses.html
{% extends "bible/base.html" %}
{% block header %}
<header class="page-header">
    <span>{{book_name}}</span>
</header>
<nav>
    <a href="/bible/{{book}}/{{prev_page}}"><button class="content_buttoms_button" {% if not prev_page %} disabled {% endif %}>Попередній розділ</button></a>
    <a href="/bible/{{book}}/{{next_page}}"><button class="content_buttoms_button" {% if not next_page %} disabled {% endif %}>Наступний розділ</button></a>
</nav>
{%endblock %}
{% block content %}
{% autoescape off %}
{% for verse in verses %}
<section onclick="openModal(this, {{verse.id}})"> # noqa
    <div class="click_no_propagation">
        <span>{{verse.chapter}}:{{verse.verse}}</span>
    </div>
    <div class="click_no_propagation">
        <span>{{verse.text}}</span>
    </div>
    {% if user %}
    <div>
        <i class="material-icons">edit</i>
    </div>
    {% endif %}
</section>
{% endfor %}
{% endautoescape %}
{% endblock %}

mysite/users/templates/users/login.html
{% extends "bible/base.html" %}

{% block content %}

{% if messages %}
<div>
    {% for message in messages %}
    <div {% if message.tags %} class="alert-{{ message.tags }}" {% endif %}>{{ message }}</div>
    {% endfor %}
</div>
{% endif %}

<form action="{% url 'users:login' %}" method="post" class="loginform">
    {% csrf_token %}
    <div>
        <label> Username:
            {{ form.username }}
        </label>
    </div>

    <div>
        <label>Password:
            {{ form.password }}
        </label>
    </div>

    <div class="grid">
        <button type="submit">Submit</button>
        <button type="reset" class="secondary">Reset</button>
    </div>
</form>

{% endblock %}

mysite/users/templates/users/signup.html
{% extends "bible/base.html" %}

{% block content %}

<div>
    <h2>Sign Up</h2>
</div>

<form method="post" action="{% url 'users:signup' %}">
    {% csrf_token %}
    <div>
        <label> Username:
            {{ form.username }}
        </label>
        <span>{{ form.errors.username }}</span>
    </div>
    <br>
    <div>
        <label> email:
            {{ form.email }}
        </label>
        <span>{{ form.errors.email }}</span>
    </div>
    <div>
        <label> Password:
            {{ form.password1 }}
        </label>
        <span>{{ form.errors.password1 }}</span>
    </div>
    <div>
        <label> Password confirmation:
            {{ form.password2 }}
        </label>
        <span>{{ form.errors.password2 }}</span>
    </div>
    <div class="grid">
        <button type="submit">Submit</button>
        <button type="reset" class="secondary">Reset</button>
    </div>
</form>

{% endblock %}